---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  collections:
    - vrsarin.k3s_ansible
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  collections:
    - vrsarin.k3s_ansible
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  collections:
    - vrsarin.k3s_ansible
  roles:
    - role: k3s_agent