all:
  hosts:
    node1:
      ansible_host: 192.168.100.10
      ip: 192.168.100.10
      access_ip: 192.168.100.10
    node2:
      ansible_host: 192.168.100.11
      ip: 192.168.100.11
      access_ip: 192.168.100.11
    node3:
      ansible_host: 192.168.100.12
      ip: 192.168.100.12
      access_ip: 192.168.100.12
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
